[package]
name = "crustabri"
authors = ["Jean-Marie Lagniez <lagniez@cril.fr>", "Emmanuel Lonca <lonca@cril.fr>", "Jean-Guy Mailly <jean-guy.mailly@u-paris.fr>"]
version = "0.1.0"
edition = "2021"
default-run = "crustabri"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "crustabri"
path = "src/lib.rs"

[[bin]]
name = "crustabri"
path = "src/main.rs"

[[bin]]
name = "crustabri_iccma23"
path = "src/main_iccma23.rs"

[[bin]]
name = "crustabri_iccma23_aba"
path = "src/main_iccma23_aba.rs"

[dependencies]
anyhow = "1.0.65"
cadical = { git = "https://github.com/elonca/cadical-rs.git", rev = "f6bd96c" }
crusti_app_helper = {path = "local_crates/crusti_app_helper-v0.1"}
lazy_static = "1.4.0"
permutator = "0.4.3"
regex = "1.6.0"
strum = "0.24.1"
strum_macros = "0.24.1"

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
paste = "1.0.11"
predicates = "2.1"
